name: SignEdit
version: 1.1
description: Ever made a mistake on a sign, and not wanted to take the sign down to fix it? Now you don't have to!
author: carl230690
website: http://www.doragoncraft.com/
main: me.carl230690.signedit.SignEdit

commands:
    signedit:
        description: Allows you to edit a sign
permissions:
    signedit.edit:
        description: Allows you to use /signedit
        default: false
    signedit.colorsonplace:
        description: Allows users to add colours to signs when placed
        default: false       
    signedit.override:
        description: Allows users to override protections.
        default: op
        children:
            signedit.edit: true
            signedit.colorsonplace: true
            signedit.admin: true
    signedit.admin:
        description: Allows you to admin SignEdit
        default: op